language: java
sudo: false # faster builds

jdk:
  - openjdk8

branches: # build only on these branches
  only:
    - master
    - dev

install:
  - travis_wait 30 mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script:
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)